'use strict';
const rates={access:{label:'СКУД',rate:180},video:{label:'Видеонаблюдение',rate:240},fire:{label:'Пожарная автоматика',rate:220},network:{label:'СКС',rate:300},power:{label:'Электроснабжение',rate:450}};
const factors={office:1,warehouse:.85,retail:1.1,production:1.3};
const solutions={office:{label:'OFFICE / РАБОЧАЯ СРЕДА',title:'Офис, готовый к ежедневной работе.',description:'Разделить зоны доступа, обеспечить связь рабочих мест и сохранить контроль над входами — без усложнения повседневных процессов.',items:['Доступ сотрудников и гостей','Сеть рабочих мест и переговорных','Контроль входов и общих зон','Оповещение и резервное питание'],cta:'Рассчитать для офиса'},warehouse:{label:'WAREHOUSE / ЛОГИСТИКА',title:'Контроль от въезда до отгрузки.',description:'Объединить периметр, погрузочные зоны и доступ смен. Учесть протяжённые трассы и разные условия освещения.',items:['Контроль въездов и погрузки','Доступ по сменам и зонам','Оптические магистрали','Резервирование важных узлов'],cta:'Рассчитать для склада'},retail:{label:'RETAIL / ТОРГОВОЕ ПРОСТРАНСТВО',title:'Безопасность без помех для покупателей.',description:'Разделить клиентские и служебные пространства, обеспечить сеть кассовой зоны и контроль ключевых маршрутов.',items:['Обзор входов и кассовых зон','Доступ в служебные помещения','Сеть торгового оборудования','Оповещение посетителей'],cta:'Рассчитать для торговли'},production:{label:'INDUSTRY / ПРОИЗВОДСТВО',title:'Инфраструктура под рабочий процесс.',description:'Учесть нагрузки, условия среды и режим работы. Разделить технологические и административные зоны.',items:['Доступ по производственным зонам','Контроль критических маршрутов','Защищённые кабельные трассы','Распределение и резерв питания'],cta:'Рассчитать для производства'}};
const calc=document.querySelector('#calc-form');
const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(n/1000)*1000)+' ₽';
let currentEstimate=null;
function calculate(){const area=Number(calc.elements.area.value);const selected=[...calc.querySelectorAll('[name="systems"]:checked')].map(x=>x.value);const output=document.querySelector('#estimate');const list=document.querySelector('#breakdown');list.replaceChildren();if(!Number.isFinite(area)||area<50||area>100000||!selected.length){output.textContent='Уточните параметры';currentEstimate=null;return;}const multiplier=factors[calc.elements.object.value]*Number(calc.elements.complexity.value);const subtotal=selected.reduce((sum,id)=>sum+rates[id].rate*area*multiplier,0);const design=Math.max(25000,subtotal*.12);const total=subtotal+design;currentEstimate={object:calc.elements.object.value,area,systems:selected,complexity:Number(calc.elements.complexity.value),min:Math.round(total*.8),max:Math.round(total*1.2)};output.textContent=money(total*.8)+' – '+money(total*1.2);const small=document.createElement('small');small.textContent='Предварительный диапазон · условные ставки';output.append(small);for(const id of selected){const li=document.createElement('li');const label=document.createElement('span');label.textContent=rates[id].label;const value=document.createElement('span');value.textContent=money(rates[id].rate*area*multiplier);li.append(label,value);list.append(li);}const li=document.createElement('li');li.textContent='Проектная подготовка: '+money(design);list.append(li);}
calc.addEventListener('input',calculate);calculate();
const menu=document.querySelector('.menu');const nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});
function selectTab(tab){const type=tab.dataset.type;const content=solutions[type];document.querySelectorAll('[role="tab"]').forEach(el=>{el.setAttribute('aria-selected',String(el===tab));el.tabIndex=el===tab?0:-1;});document.querySelector('#solution-panel').setAttribute('aria-labelledby',tab.id);document.querySelector('#solution-label').textContent=content.label;document.querySelector('#solution-title').textContent=content.title;document.querySelector('#solution-description').textContent=content.description;document.querySelector('#solution-cta').textContent=content.cta;document.querySelector('#solution-cta').dataset.type=type;const list=document.querySelector('#solution-list');list.replaceChildren();content.items.forEach((item,index)=>{const li=document.createElement('li');const span=document.createElement('span');span.textContent=String(index+1).padStart(2,'0');li.append(span,document.createTextNode(item));list.append(li);});}
document.querySelectorAll('[role="tab"]').forEach(tab=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[role="tab"]')];let index=tabs.indexOf(tab);if(e.key==='ArrowRight')index=(index+1)%tabs.length;else if(e.key==='ArrowLeft')index=(index-1+tabs.length)%tabs.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=tabs.length-1;else return;e.preventDefault();selectTab(tabs[index]);tabs[index].focus();});});
document.querySelector('#solution-cta').addEventListener('click',e=>{calc.elements.object.value=e.currentTarget.dataset.type||'office';calculate();});document.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>{calc.querySelector('[value="'+button.dataset.service+'"]').checked=true;calculate();document.querySelector('#calculator').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}));
document.querySelector('#transfer').addEventListener('click',e=>{if(!currentEstimate){e.preventDefault();calc.reportValidity();document.querySelector('#estimate').textContent='Введите площадь и выберите систему';return;}const names={office:'Офис',warehouse:'Склад',retail:'Торговля',production:'Производство'};document.querySelector('[name="message"]').value=names[currentEstimate.object]+', '+currentEstimate.area+' м². Системы: '+currentEstimate.systems.map(id=>rates[id].label).join(', ')+'. Предварительный бюджет: '+money(currentEstimate.min)+' – '+money(currentEstimate.max)+'.\nДополнительные сведения: ';});
// Set an HTTPS endpoint in config.js when a server accepting this contract is ready.
async function submitLead(payload){const endpoint=window.NEXUS_CONFIG?.leadEndpoint;if(!endpoint)return{mode:'demo'};const url=new URL(endpoint,location.origin);if(url.protocol!=='https:'&&url.hostname!=='localhost')throw new Error('Недопустимый адрес сервиса');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});if(!response.ok)throw new Error('Ошибка отправки');return{mode:'sent'};}finally{clearTimeout(timeout);}}
const lead=document.querySelector('#lead-form');lead.addEventListener('submit',async e=>{e.preventDefault();if(!lead.reportValidity())return;const button=lead.querySelector('button[type="submit"]');const status=document.querySelector('#form-status');const values=new FormData(lead);const payload={version:1,name:String(values.get('name')).trim(),company:String(values.get('company')).trim(),email:String(values.get('email')).trim(),message:String(values.get('message')).trim(),estimate:currentEstimate,consent:true,source:'nexus-systems',createdAt:new Date().toISOString()};if(payload.name.length<2||payload.message.length<10){status.textContent='Введите имя и описание задачи без лишних пробелов.';return;}button.disabled=true;status.textContent='Подготовка заявки…';try{const result=await submitLead(payload);status.textContent=result.mode==='demo'?'Демо-заявка подготовлена. Данные не отправлены и не сохранены.':'Заявка отправлена. Спасибо!';}catch{status.textContent='Не удалось отправить заявку. Попробуйте ещё раз позже.';}finally{button.disabled=false;}});
